spring.application.name=itam

spring.datasource.url=jdbc:postgresql://localhost:5435/itam_db
spring.datasource.username=user
spring.datasource.password=user

# Cambiamos temporalmente a "none" para que Spring no falle si estás probando
# antes de haber creado tus clases @Entity. Luego lo regresas a "validate".
spring.jpa.hibernate.ddl-auto=none

spring.docker.compose.enabled=false
spring.jpa.open-in-view=false