spring.application.name=itam

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:itam_db}
spring.datasource.username=${DB_USER:user}
spring.datasource.password=${DB_PASSWORD:user}

spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false

spring.docker.compose.enabled=false

server.port=${SERVER_PORT:8080}
