services:
  postgres:
    image: postgres:16
    container_name: itam_postgres

    restart: unless-stopped

    environment:
      POSTGRES_DB: itam_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user

    ports:
      - "5435:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d

volumes:
  postgres_data: